### ISSUE TITLE
not able to build openCV in cmake. though compiler is found

### ISSUE THREAD

**Issue by Abhi-1725** [sgratzl/oogl#1]
Hello team,

i am able to configure via cmake but unable to build openCV in cmake.
as shown in pic below:

![image](https://user-images.githubusercontent.com/33417745/33037391-0d1f1d10-ce3a-11e7-9b58-3593a547a1c6.png)

I need to get a cmake window of this  type as shown below :  could you please assist. ASAP

![image](https://user-images.githubusercontent.com/33417745/33037531-890e08b4-ce3a-11e7-8c9b-8c351e7138b6.png)

**Comment by sgratzl** [comment]
this project doesn't use OpenCV. It is an (old) project for creating OpenGL projects

**Comment by Abhi-1725** [comment]
i did not understand to which project are you referring to ?

**Comment by Abhi-1725** [comment]
cmake is not finding openCV directories and path. how should i get it ?
